### ISSUE TITLE
Spam Error Logs when Out Moon

### ISSUE THREAD

**Issue by DHStyle541** [AndreyMrovol/LethalRichPresence#1]
![image](https://github.com/AndreyMrovol/LethalRichPresence/assets/154591650/a17af25f-448c-4e63-94cf-0615ebbebf80)

**Comment by AndreyMrovol** [comment]
Hey, thank you @DHStyle541 for reporting the issue - I pushed a new version to Thunderstore, see if it fixes your problem.
