### ISSUE TITLE
Console spam when hosting, no rich presence when in Discord

### ISSUE THREAD

**Issue by Crystalwarrior** [AndreyMrovol/LethalRichPresence#10]
It seems to just spam the console with a number and no further information every second

![image](https://github.com/AndreyMrovol/LethalRichPresence/assets/3470436/e5dd393e-7663-4402-9f83-1dbd85c5069c)

**Comment by AndreyMrovol** [comment]
Hey, could you send me your whole .log file? The messages that you're seeing are the debugging leftovers (sorry!), and from that alone I'm unable to know what's happening.

**Comment by Crystalwarrior** [comment]
> Hey, could you send me your whole .log file? The messages that you're seeing are the debugging leftovers (sorry!), and from that alone I'm unable to know what's happening.

Alright! I noticed the configuration setting to enable/disable debug logging (which is true by default), I'll try a run of the game and send you the full log

**Comment by Crystalwarrior** [comment]
[LogOutput.log](https://github.com/AndreyMrovol/LethalRichPresence/files/13850997/LogOutput.log)

@AndreyMrovol here's the .log file!

**Comment by AndreyMrovol** [comment]
Hey, are you sure the mod is enabled? From quick search I cannot see any logs left by my mod 
![image](https://github.com/AndreyMrovol/LethalRichPresence/assets/32998721/7b8b7932-72e1-497d-a544-e7c3be7ca8a3)
(not even BepInEx "plugin started" message) 

---

from my hosted and started game:
![image](https://github.com/AndreyMrovol/LethalRichPresence/assets/32998721/c27eaf35-fa11-4dba-a1f0-ae5b659de1b4)
![image](https://github.com/AndreyMrovol/LethalRichPresence/assets/32998721/7a656258-1b2a-44ac-8806-ab45fe0e1f28)
