### ISSUE TITLE
Discord Rich Presence no update

### ISSUE THREAD

**Issue by DHStyle541** [AndreyMrovol/LethalRichPresence#11]
Hi, The DRP no Update
Ex: 
![image](https://github.com/AndreyMrovol/LethalRichPresence/assets/154591650/bf182e65-c8f4-4382-b462-9ee7e89c9c37)

i'm in Experment but DRP said In Company, and This is 3th Quota 

*Edit
Found error logs only like this
![image](https://github.com/AndreyMrovol/LethalRichPresence/assets/154591650/748d1b6a-e136-4e7f-8604-afe2918e2f38)

And The Custom ID Discord, add the wiki please for Custom
only mainmenu, inorbit, fired work but %currentmoon% %weather% no work if custom ID Discord [make disappear Logo DRP]

**Comment by AndreyMrovol** [comment]
Hey @DHStyle541, thanks for reporting the issue - could you send me your config file? Are you playing online or on LAN? What mods are you using?

With custom Discord ID, you need to setup your own assets in [Discord Developer Portal](https://discord.com/developers/applications) - all images defined in my app are displayed [here](https://github.com/AndreyMrovol/LethalRichPresence/tree/main/DiscordImages)

**Comment by DHStyle541** [comment]
[LethalRichPresence.txt](https://github.com/AndreyMrovol/LethalRichPresence/files/13849494/LethalRichPresence.txt)

^ my Config LRP "Can't Upload the .cfg so i Changed to .txt"

I testing on Online.

My Modpack:
![image](https://github.com/AndreyMrovol/LethalRichPresence/assets/154591650/5bf6e879-4500-414a-89fe-0f6cf33da450)

**Comment by DHStyle541** [comment]
So when fix this is problem :/, i want using this is because have Join using Discord
but problem is Discord no auto update

**Comment by AndreyMrovol** [comment]
Hey, does the problem still exist? If so, please send me your .log file from the session where the issue is happening.

**Comment by DHStyle541** [comment]
i test only BepinEx and Latest LRP but still no update Discord. i'm no jk and error still same like first Image 
I wouldn't complain if there weren't any problems :/

**Comment by AndreyMrovol** [comment]
Please send me your .log file from your BepInEx folder - without it I'm not able to pinpoint where the issue happens.

**Comment by DHStyle541** [comment]
[LogOutput.log](https://github.com/AndreyMrovol/LethalRichPresence/files/13939962/LogOutput.log)

https://github.com/AndreyMrovol/LethalRichPresence/assets/154591650/e7bc998e-8623-4021-b297-7149048d599d

^ This is Video but Kinda Blur cause Max Size 10mb :/

**Comment by AndreyMrovol** [comment]
Hey, @DHStyle541 - Can you delete your config file to auto-generate a default one? v0.5.0 had a significant rework of config file, which might've broken something in your settings.

Also - please enable debug logs in your BepInEx:

Go to config editor -> Bepinex/config/Bepinex.cfg
![image](https://github.com/AndreyMrovol/LethalRichPresence/assets/32998721/6a3a66fa-a644-4879-940f-616e23ddd3e9)

then to Logging.Disk -> `LogLevels` -> **change the setting to `All`**
![image](https://github.com/AndreyMrovol/LethalRichPresence/assets/32998721/cf7facba-523b-4c5d-8f98-2beb5d098f06)

After you've done that, please try playing your game again and upload your saved .log file

**Comment by DHStyle541** [comment]
I'm not using Thunderstore App or Manager like that
i install Manual, and ofc i already delete the LRP.cfg before intall and testing. and problem still same

if i see on log like totaly normal but on Discord the DRP no update.
only that problem

https://thunderstore.io/c/lethal-company/p/Giltong/LethalCompanyDRP/
i'm using this is normal always update drp when going Expriment>Vow>Assurance>Company and Player quit Join quit join auto update

[LogOutput.log](https://github.com/AndreyMrovol/LethalRichPresence/files/13951242/LogOutput.log)

**Comment by AndreyMrovol** [comment]
Hey, thanks for the response - from what i can see, all planets/game phases are resolved correctly, so I think this issue might be related to #6 (MoreCompany and LAN sessions).

Are you playing on LAN?

**Comment by DHStyle541** [comment]
I never testing on Lan. always Online :/

**Comment by AndreyMrovol** [comment]
> I never testing on Lan. always Online :/

Ok, I managed to reproduce the issue using LethalRichPresence v0.5.2 and MoreCompany v1.7.4 - trying to find a fix

**Comment by AndreyMrovol** [comment]
@DHStyle541 - Are you using game version 49?

**Comment by DHStyle541** [comment]
Ya i using LC Version 49

**Comment by DHStyle541** [comment]
@AndreyMrovol 
Yes, I'm Using LC Version 49

I Testing All version LRP to 0.1.1 > 0.5.3
0.1.1 > 0.2.2 [ Normal And Discord Always Update ]
0.3.0 > 0.5.3 No Auto Update ( already Delete Config ) and still No Update for Discord

Edit*
0.3.0 > 0.4.1 [ Work Fine but need Delete Config "LethalCompanyDRP" ]
0.5.0 > Latest version [ Still Not Work Already Delete LRP and "LethalCompanyDRP" Config, Issue Still same ]

**Comment by AndreyMrovol** [comment]
I've found the exact issue: after starting the game, the reported `Party ID` and `Party leader` variables are null, which prevents Rich Presence from updating (invalid values)
```
[Debug  :LethalRichPresence] In orbit?: True
[Debug  :LethalRichPresence] Players: 1 / 16
[Debug  :LethalRichPresence] Party ID: 109775243962567952
[Debug  :LethalRichPresence] Party leader: andrey
```
```
[Debug  :LethalRichPresence] In orbit?: False
[Debug  :LethalRichPresence] Players: 1 / 16
[Debug  :LethalRichPresence] Party ID: 
[Debug  :LethalRichPresence] Party leader: 
```

This is due to vanilla behavior of closing lobby after starting game without ability to drop-in (ShipLobby, AdvancedCompany allows this). I did not test this in vanilla setting, and for that I'm really sorry.

@DHStyle541: I've just pushed v0.5.4 to Thunderstore - please check if it resolves your issue and let me know.

**Comment by DHStyle541** [comment]
still same :)) so sad

**Comment by AndreyMrovol** [comment]
@DHStyle541 sorry for that - i've just pushed v0.5.5 to Thunderstore - please check if it resolves your issue and let me know.

**Comment by DHStyle541** [comment]
For now it's normal and working well :), I'll let you know if there are problems when playing with my friends

Thank You :)
