### ISSUE TITLE
Stuttering while in game

### ISSUE THREAD

**Issue by cdusold** [AndreyMrovol/LethalRichPresence#13]
I've narrowed down the stutter I'm getting in game to this mod. There's a bit of terminal spam when it happens. I'll see if I can't do a root cause analysis when I get some time later. If the Discord API call is being launched in a new thread, the io shouldn't have any issues though.

**Comment by AndreyMrovol** [comment]
Hi, thanks for your report - I'll look into ways of minimizing console/IO output. 
In the meantime - have you tried measuring the impact after disabling debug logging in mod's config?

**Comment by cdusold** [comment]
I was able to recreate the stuttering without this mod. I'm doing more analysis. I'll close this issue. Thank you for responding. The spam appears to be warnings that the audio spatializer plugin is not working. I'm not sure if that's the cause or the symptom of something else, either way, it's not this plugin, which seems to be working great. Not sure why disabling it helped before, but I think it was a coincidence.

**Comment by cdusold** [comment]
Oh. The Dissonance plugin is getting overwhelmed, so unloading mods decreases the CPU load (which isn't spiking? But I don't know what's going on there).
