### ISSUE TITLE
InternalError at LethalRichPresence.DiscordAbstraction.CreateDiscord()

### ISSUE THREAD

**Issue by IogaMaster** [AndreyMrovol/LethalRichPresence#14]
![image](https://github.com/AndreyMrovol/LethalRichPresence/assets/67164465/655a0915-2c21-482f-bc5a-4f7e4ba347a3)

# Mods Used
These Are the only mods I have
![image](https://github.com/AndreyMrovol/LethalRichPresence/assets/67164465/aeca7dfe-410a-4086-9438-9fd9730db322)
![image](https://github.com/AndreyMrovol/LethalRichPresence/assets/67164465/64f17b3a-7df8-4363-abbd-6bb279db59fd)

**Comment by AndreyMrovol** [comment]
Hey, thanks for your report - quick questions:
1. Have you changed your config file? This might be an issue with wrong appID
2. Are you on Linux?
3. Did it happen in previous versions?

**Comment by IogaMaster** [comment]
1. I did after the error, to confirm if the app was broken. No matter the AppID the error remains.
2. Yes, NixOS. Using proton experimental and r2modman
3. I do not know

**Comment by AndreyMrovol** [comment]
I've quickly tested - this is an issue when mod cannot connect with Discord on your PC. Have you tried using some bridging software (for example https://github.com/0e4ef622/wine-discord-ipc-bridge)?

**Comment by IogaMaster** [comment]
Just tried it
Exact same issue is present

**Comment by AndreyMrovol** [comment]
maybe this will help? https://github.com/openglfreak/winestreamproxy

**Comment by AndreyMrovol** [comment]
Hey @IogaMaster, checking in to confirm - did you manage to resolve your issue?

**Comment by IogaMaster** [comment]
Sorry, I've been a little busy. I will try again this weekend.

**Comment by IogaMaster** [comment]
Sorry for the delay, I can confirm it now works using wine-discord-ipc

**Comment by AndreyMrovol** [comment]
Hey, that's nice to hear - thank you for the follow-up!  😇
