### ISSUE TITLE
Custom Weather not Showing DRP

### ISSUE THREAD

**Issue by DHStyle541** [AndreyMrovol/LethalRichPresence#15]
Hi, The Discord Rich Pressence not showing custom weather. but vanilla working fine

No Error Logs

![image](https://github.com/AndreyMrovol/LethalRichPresence/assets/154591650/360caa33-30af-4396-bd3d-de5a51983900)

And my DRP Custom become using your ID, idk why this is happend. ( only going custom weather ) (https://thunderstore.io/c/lethal-company/p/stormytuna/HellWeather/)
![image](https://github.com/AndreyMrovol/LethalRichPresence/assets/154591650/3356615e-62f8-47a1-8431-e02e1245002c)

Normaly like this is my DRP Custom ( Custom Moons: Atlas | Weather: Foggy )
![image](https://github.com/AndreyMrovol/LethalRichPresence/assets/154591650/85b3ba13-c99a-4fe5-927e-c0b2222250c2)

and i already add Hell to Discord Assets but still not work
![image](https://github.com/AndreyMrovol/LethalRichPresence/assets/154591650/ea795226-e828-49e1-b031-51630170fc90)

**Comment by AndreyMrovol** [comment]
Hey, thanks for reporting this issue.

Could you send me your whole .log? This *should* work, but for some reason isn't.

**Comment by DHStyle541** [comment]
[LogOutput.log](https://github.com/AndreyMrovol/LethalRichPresence/files/14208673/LogOutput.log)

here we go

**Comment by AndreyMrovol** [comment]
This is what I'm getting (from quick testing)
```
[Debug  :LethalRichPresence] Resolved |%currentplanet%| to |56-Vow|
[Debug  :LethalRichPresence] Resolved |%&currentplanet%| to |56-vow|
[Debug  :LethalRichPresence] Resolved |%currentweather%| to |Hell|
[Debug  :LethalRichPresence] Resolved |%&currentweather%| to |hell|
```

**Comment by AndreyMrovol** [comment]
Have you tried using the latest version of LethalRichPresence?

**Comment by DHStyle541** [comment]
yes i using latest version 
![image](https://github.com/AndreyMrovol/LethalRichPresence/assets/154591650/c9537a19-8078-4755-a4c6-9cf5fa93e9c2)

**Comment by AndreyMrovol** [comment]
This is very weird.

Could you enable debug logging for me? (method shown here: https://github.com/AndreyMrovol/LethalRichPresence/issues/11#issuecomment-1893315750)

**Comment by DHStyle541** [comment]
ah nvm Mybad. my config get reset byself idk why

sry :(

![image](https://github.com/AndreyMrovol/LethalRichPresence/assets/154591650/cee2a339-c25c-4b55-8318-184b15bbfc7e)

**Comment by AndreyMrovol** [comment]
No worries, I'm glad it's working for you :D
