### ISSUE TITLE
Lethal Company thumbnail showed up briefly, then disappeared

### ISSUE THREAD

**Issue by SheepCommander** [AndreyMrovol/LethalRichPresence#2]
![image](https://github.com/AndreyMrovol/LethalRichPresence/assets/66646514/560541cb-a1b8-4663-a85c-6d9751e4a1b8)

btw I really like the default settings for this one, I like them more than the Discord RPC that this is based on

**Comment by AndreyMrovol** [comment]
@SheepCommander, thanks for your feedback! I pushed a new version to Thunderstore, which displays game logo when in main menu.

![image](https://github.com/AndreyMrovol/LethalRichPresence/assets/32998721/4ae2ffe0-a66f-4183-8e97-75a4f6c24b59)

**Comment by SheepCommander** [comment]
Awesome! Thank you so much
