### ISSUE TITLE
Compatibility listed as ClientOptional for some reason

### ISSUE THREAD

**Issue by cdusold** [AndreyMrovol/LethalRichPresence#20]
https://github.com/AndreyMrovol/LethalRichPresence/blob/f751ca0c0aca0f566bc2a3837dd32941c299a5d2/LethalRichPresence/LobbyCompatibility.cs#L27

The ClientOptional tag is only for when the host needs it, and others may exclude it. This mod should be ClientOnly based on conversation on the Lethal Modding Discord: https://discord.com/channels/1168655651455639582/1189910603540742204/1279197900097978450

**Comment by AndreyMrovol** [comment]
Fixed in #21
