### ISSUE TITLE
MoreCompany Mod support

### ISSUE THREAD

**Issue by FLozyXD** [AndreyMrovol/LethalRichPresence#6]
Would be great if maximum players value was synced with maximum amount of players set with MoreCompany. Not sure yet, but I think that if there are 4/10 players in a lobby, discord may not let you join because there are already 4 players.

**Comment by AndreyMrovol** [comment]
Hey, thanks for reporting the issue - I tested the compatibility with BiggerLobby mod (which i used), so i forgot to check with other mods that increase lobby sizes. I think I found the solution, I'll try to create a fix today/tomorrow after some testing.

**Comment by AndreyMrovol** [comment]
Pushed an update to Thunderstore - check if it fixes the issue!

**Comment by FLozyXD** [comment]
Yep, now it shows amount of players correctly. But seems like there is another issue. My friend can't join through discord invite. He says it's just an infinite loading and nothing happens. Was it working fine for Bigger Lobby?

**Comment by AndreyMrovol** [comment]
The invite feature is horribly untested - it was not tested with any "big lobby" mods, and it _should_ work fine for normal lobbies (it was not tested properly)

**Comment by AndreyMrovol** [comment]
@FLozyXD Please check v0.5.2 - the issue should be fully resolved.
